In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('CarPrice_Assignment.csv')
df = pd.DataFrame(data)
df[['company', 'model']] = df['CarName'].str.split(' ', n =1, expand=True)
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,company,model
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero,giulia
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero,stelvio
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero,Quadrifoglio
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102,5500,24,30,13950.0,audi,100 ls
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115,5500,18,22,17450.0,audi,100ls
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,23,28,16845.0,volvo,145e (sw)
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,8.7,160,5300,19,25,19045.0,volvo,144ea
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,3.58,2.87,8.8,134,5500,18,23,21485.0,volvo,244dl
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,3.01,3.40,23.0,106,4800,26,27,22470.0,volvo,246
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114,5400,19,25,22625.0,volvo,264gl

In [3]:
X_train = df.drop(['car_ID','CarName','model','price'], axis = 1)
X_train

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,company
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,alfa-romero
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,alfa-romero
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,alfa-romero
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,audi
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,volvo
201,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,volvo
202,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,volvo
203,-1,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,volvo
204,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,volvo

In [4]:
y = df['price']
y_train = pd.DataFrame(y)
y_train

       price
0    13495.0
1    16500.0
2    16500.0
3    13950.0
4    17450.0
..       ...
200  16845.0
201  19045.0
202  21485.0
203  22470.0
204  22625.0

[205 rows x 1 columns]

In [5]:
X_train = pd.get_dummies(X_train, columns = ['symboling','company', 'fueltype','aspiration', 'doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem'])
X_train.head()

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,...,cylindernumber_twelve,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,...,False,False,False,False,False,False,False,True,False,False
1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,...,False,False,False,False,False,False,False,True,False,False
2,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,...,False,False,False,False,False,False,False,True,False,False
3,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,...,False,False,False,False,False,False,False,True,False,False
4,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,...,False,False,False,False,False,False,False,True,False,False

In [6]:
def Z_normalise(X_train):
    mu = X_train.mean(axis = 0)
    std = np.std(X_train)
    X_train = ((X_train - mu)/std)
    return X_train

In [7]:
X_train1= pd.DataFrame(Z_normalise(X_train))
X_train1
m = len(X_train1)
X_train1

C:\Users\hiaga\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py:3800: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,...,cylindernumber_twelve,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,0.174483,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
1,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,0.174483,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
2,-0.708596,-0.231513,-0.190566,-0.543527,0.514882,0.604046,-2.404880,0.685946,-0.288349,1.264536,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
3,0.173698,0.207256,0.136542,0.235942,-0.420797,-0.431076,-0.517266,0.462183,-0.035973,-0.053668,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
4,0.107110,0.207256,0.230001,0.235942,0.516807,0.218885,-0.517266,0.462183,-0.540725,0.275883,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.721873,1.198549,1.398245,0.728239,0.763241,0.339248,1.666445,-0.336970,-0.162161,0.250533,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
201,1.721873,1.198549,1.351515,0.728239,0.949992,0.339248,1.666445,-0.336970,-0.364062,1.416637,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
202,1.721873,1.198549,1.398245,0.728239,0.878757,1.109571,0.926204,-1.232021,-0.338824,0.757535,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014
203,1.721873,1.198549,1.398245,0.728239,1.273437,0.435538,-1.183483,0.462183,3.244916,0.047732,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,3.041381,-0.070014,-0.920243,-0.214286,-0.070014
204,1.721873,1.198549,1.398245,0.728239,0.975021,0.339248,1.666445,-0.336970,-0.162161,0.250533,...,-0.070014,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014

In [8]:
def normal_equation(X, y):
  """
  Calculates the coefficients of a linear regression model using the normal equation.

  Parameters:
    X (numpy.ndarray): The design matrix (features).
    y (numpy.ndarray): The target variable.

  Returns:
    numpy.ndarray: The coefficients of the linear regression model.
  """

  # Add a column of ones for the intercept term
  X_b = np.c_[np.ones((X.shape[0], 1)), X]

  # Calculate the coefficients using the normal equation
  theta = np.linalg.pinv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

  return theta

In [9]:
X_train = X_train1.to_numpy()
y_train = y_train.to_numpy()
theta= normal_equation(X_train, y_train)
m,_ = X_train.shape
print(theta)

[[13276.71057073]
 [ 1254.0703965 ]
 [-1682.8999951 ]
 [ 1534.80030722]
 [ -615.31053667]
 [ 3159.17659518]
 [ 3794.35040398]
 [ -821.05840754]
 [ -455.32848358]
 [-2928.24840434]
 [  259.85845269]
 [  961.42316191]
 [  -51.82643501]
 [  691.35861311]
 [  -71.76073927]
 [   91.96417849]
 [  141.39300048]
 [  139.72699812]
 [ -117.69365806]
 [ -310.49009972]
 [  -84.19696169]
 [  308.23471486]
 [  599.12755235]
 [ 1470.9584897 ]
 [  913.75305126]
 [ -288.52412049]
 [ -638.83116015]
 [  -67.31235419]
 [  -99.69489367]
 [   72.47414386]
 [ -106.54315737]
 [  -43.71026287]
 [ -143.85430859]
 [ -801.23128211]
 [ -154.28900562]
 [ -428.19756924]
 [ -555.66551164]
 [  258.95384717]
 [  769.72718852]
 [ -133.39311118]
 [  612.04988772]
 [ -148.62924246]
 [ -431.26808486]
 [ -202.36426499]
 [  -21.68916698]
 [   64.16837597]
 [   84.82183061]
 [  107.26033944]
 [  923.13768704]
 [ -923.13768704]
 [ -301.1215405 ]
 [  301.1215405 ]
 [   28.6771364 ]
 [  -28.6771364 ]
 [  394.15994478]
 [   58.58425548]
 [ -223.01515697]
 [   72.73210509]
 [  -25.43357711]
 [  -38.81956333]
 [ -106.65672784]
 [  125.25581298]
 [ -610.79983912]
 [  610.79983912]
 [   29.20620807]
 [ -416.79356833]
 [ -250.90527112]
 [  342.64422851]
 [  147.66853562]
 [ -756.23880738]
 [  530.7544533 ]
 [  430.79046512]
 [ -710.38618524]
 [   45.63613294]
 [  -86.18289914]
 [  539.52183332]
 [ -124.93228891]
 [  530.7544533 ]
 [ -419.00903898]
 [  165.40217579]
 [ -274.96338328]
 [  923.13768704]
 [ -102.7691466 ]
 [ -326.28201373]
 [ -253.63596253]
 [  -29.43276031]]

In [10]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Predict using matrix multiplication for all samples at once
pred = np.dot(X_train, theta[1:])+theta[0]

# Compute root mean squared error (RMSE)
errors = mean_squared_error(y_train, pred, squared=False)

# Normalize by the mean of y_train
nrmse = errors / np.mean(y_train)

# Print the result with formatted output
print(f'NRMSE: {nrmse:.3f}')

NRMSE: 0.109

C:\Users\hiaga\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [11]:
from sklearn.metrics import r2_score  
r2 = r2_score(y_train,pred) 
print('r2 score for model is', 100* r2)

r2 score for model is 96.72954581584331